---
# tasks file for deb-cis

- name: Check OS version and family
  fail:
      msg: "This role can only be run agaist Debian/Ubuntu Distros. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when:
      - not ansible_os_family == "Debian"
  tags:
      - always

- name: Check ansible version
  fail:
      msg: You must use ansible 2.3 or greater!
  when: not ansible_version.full is version_compare('2.3', '>=')
  tags:
      - always

- include_tasks: section1-partitions.yml
  when: cis_partitions
  tags: partitions

- include_tasks: section1.yml
  when: cis_section1
  tags: section1


- include_tasks: section2-prelims.yml
  when: cis_section2
  tags: section2
  
- include_tasks: section2.yml
  when: cis_section2
  tags: section2

- include_tasks: section3.yml
  when: cis_section3
  tags: section3

- include_tasks: section4.yml
  when: cis_section4
  tags: section4

- include_tasks: section5.yml 
  when: cis_section5
  tags: section5

- include_tasks: section6.yml
  when: cis_section6
  tags: section6

- include_tasks: lynis.yml
  when: cis_lynis_fix

- include_tasks: section99.yml
  when: cis_section99
  tags: lockdown

- include_tasks: port.yml
  when: open_custom_port
  tags: port