#################### Iptables #####################
- name: "SECTION 99 | LOCKDOWN | Block SSH Login"
  iptables:
    chain: "{{ item }}"
    flush: yes
  with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]
  when:
      - cis_99_deny_ssh
  tags:
    - level2
    - lockdown

###############################################################

- name: "SECTION 99 | LOCKDOWN | Further Harden sshd_config"
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      # SECTION 99
      # 99.5.2.1
      PubkeyAuthentication yes
      PasswordAuthentication no
      KbdInteractiveAuthentication no 
      KerberosAuthentication no
      ChallengeResponseAuthentication no 
      HostbasedAuthentication no 
      GSSAPIAuthentication no 
      GSSAPIKeyExchange no
      # 99.5.2.2
      RekeyLimit 512M\s+6h
      # 99.5.2.3
      AllowAgentForwarding no
      AllowTcpForwarding no 
      AllowStreamLocalForwarding no 
      PermitTunnel no 
      PermitUserRC no 
      GatewayPorts no
      # 99.5.2.5
      StrictModes yes
      # 99.5.2.8
      UsePrivilegeSeparation sandbox
      AcceptEnv LANG LC
  when:
      - cis_99_harden_sshd
  tags:
    - level2
    - lockdown

- name: "SECTION 99 | LOCKDOWN | Further Harden hosts.deny"
  lineinfile:
    path: /etc/hosts.deny
    line: 'ALL: ALL'
    state: present
    create: yes
  when:
      - cis_99_harden_hosts
  tags:
    - level2
    - lockdown

- name: "SECTION 99 | LOCKDOWN | Remove authorized_keys file"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
      - /home/ec2-user/.ssh/authorized_keys
      - /home/centos/.ssh/authorized_keys
      - /root/.ssh/authorized_keys
  when:
      - cis_99_remove_keys
  tags:
    - level2
    - lockdown