---
# Preliminary tasks

# Individual service checks
- name: "Section 2 | PRELIM | Check for xinetd service"
  shell: "set -o pipefail;
      systemctl show xinetd | grep LoadState | cut -d = -f 2"
  args:
      executable: /bin/bash
  register: xinetd_service_status
  changed_when: false
  check_mode: false

- name: "Section 2 | PRELIM | Check for openbsd-inetd service"
  shell: "set -o pipefail;
      dpkg -s openbsd-inetd | grep -o 'ok installed'; true"
  args:
      executable: /bin/bash
  register: openbsd_inetd_service_status
  changed_when: false
  check_mode: false

- name: "Section 2 | PRELIM | Check for ntpd service"
  shell: "set -o pipefail;
      systemctl show {{ ntp_service[ansible_os_family] }} | grep LoadState | cut -d = -f 2"
  args:
      executable: /bin/bash
  register: ntpd_service_status
  changed_when: false
  check_mode: false

- name: "Section 2 | PRELIM | Check for chronyd service"
  shell: "set -o pipefail;
      systemctl show {{ chrony_service[ansible_os_family] }} | grep LoadState | cut -d = -f 2"
  args:
      executable: /bin/bash
  register: chronyd_service_status
  changed_when: false
  check_mode: false

- name: "Section 2 | PRELIM | Check for avahi-daemon service"
  shell: "set -o pipefail;
      systemctl show avahi-daemon | grep LoadState | cut -d = -f 2"
  args:
      executable: /bin/bash
  register: avahi_service_status
  changed_when: false
  check_mode: false

- name: "Section 2 | PRELIM | Check for cups service"
  shell: "set -o pipefail;
      systemctl show cups | grep LoadState | cut -d = -f 2"
  args:
      executable: /bin/bash
  register: cups_service_status
  changed_when: false
  check_mode: false

- name: "Section 2 | PRELIM | Check for dhcpd service"
  shell: "set -o pipefail;
      systemctl show dhcpd | grep LoadState | cut -d = -f 2"
  args:
      executable: /bin/bash
  register: dhcpd_service_status
  changed_when: false
  check_mode: false

- name: "Section 2 | PRELIM | Check for slapd service"
  shell: "set -o pipefail;
      systemctl show slapd | grep LoadState | cut -d = -f 2"
  args:
      executable: /bin/bash
  register: slapd_service_status
  changed_when: false
  check_mode: false

- name: "Section 2 | PRELIM | Check for nfs service"
  shell: "set -o pipefail;
      systemctl show nfs | grep LoadState | cut -d = -f 2"
  args:
      executable: /bin/bash
  register: nfs_service_status
  changed_when: false
  check_mode: false

- name: "Section 2 | PRELIM | Check for rpcbind service"
  shell: "set -o pipefail;
      systemctl show rpcbind | grep LoadState | cut -d = -f 2"
  args:
      executable: /bin/bash
  register: rpcbind_service_status
  changed_when: false
  check_mode: false

- name: "Section 2 | PRELIM | Check for named service"
  shell: "set -o pipefail;
      systemctl show named | grep LoadState | cut -d = -f 2"
  args:
      executable: /bin/bash
  register: named_service_status
  changed_when: false
  check_mode: false

- name: "Section 2 | PRELIM | Check for vsftpd service"
  shell: "set -o pipefail;
      systemctl show vsftpd | grep LoadState | cut -d = -f 2"
  args:
      executable: /bin/bash
  register: vsftpd_service_status
  changed_when: false
  check_mode: false

- name: "Section 2 | PRELIM | Check for httpd service"
  shell: "set -o pipefail;
      systemctl show apache2 | grep LoadState | cut -d = -f 2"
  args:
      executable: /bin/bash
  register: httpd_service_status
  changed_when: false
  check_mode: false

- name: "Section 2 | PRELIM | Check for dovecot service"
  shell: "set -o pipefail;
      systemctl show dovecot | grep LoadState | cut -d = -f 2"
  args:
      executable: /bin/bash
  register: dovecot_service_status
  changed_when: false
  check_mode: false

- name: "Section 2 | PRELIM | Check for smb service"
  shell: "set -o pipefail;
      systemctl show smbd | grep LoadState | cut -d = -f 2"
  args:
      executable: /bin/bash
  register: smb_service_status
  changed_when: false
  check_mode: false

- name: "Section 2 | PRELIM | Check for squid service"
  shell: "set -o pipefail;
      systemctl show squid | grep LoadState | cut -d = -f 2"
  args:
      executable: /bin/bash
  register: squid_service_status
  changed_when: false
  check_mode: false

- name: "Section 2 | PRELIM | Check for snmpd service"
  shell: "set -o pipefail;
      systemctl show snmpd | grep LoadState | cut -d = -f 2"
  args:
      executable: /bin/bash
  register: snmpd_service_status
  changed_when: false
  check_mode: false

- name: "Section 2 | PRELIM | Check for ypserv service"
  shell: "set -o pipefail;
      systemctl show nis | grep LoadState | cut -d = -f 2"
  args:
      executable: /bin/bash
  register: ypserv_service_status
  changed_when: false
  check_mode: false

- name: "Section 2 | PRELIM | Check for rsh.socket service"
  shell: "set -o pipefail;
      systemctl show rsh.socket | grep LoadState | cut -d = -f 2"
  args:
      executable: /bin/bash
  register: rsh_service_status
  changed_when: false
  check_mode: false

- name: "Section 2 | PRELIM | Check for rlogin.socket service"
  shell: "set -o pipefail;
      systemctl show rlogin.socket | grep LoadState | cut -d = -f 2"
  args:
      executable: /bin/bash
  register: rlogin_service_status
  changed_when: false
  check_mode: false

- name: "Section 2 | PRELIM | Check for rexec.socket service"
  shell: "set -o pipefail;
      systemctl show rexec.socket | grep LoadState | cut -d = -f 2"
  args:
      executable: /bin/bash
  register: rexec_service_status
  changed_when: false
  check_mode: false

- name: "Section 2 | PRELIM | Check for telnet service"
  shell: "set -o pipefail;
      systemctl show telnetd | grep LoadState | cut -d = -f 2"
  args:
      executable: /bin/bash
  register: telnet_service_status
  changed_when: false
  check_mode: false

- name: "Section 2 | PRELIM | Check for tftp service"
  shell: "set -o pipefail;
      systemctl show tftpd-hpa | grep LoadState | cut -d = -f 2"
  args:
      executable: /bin/bash
  register: tftp_service_status
  changed_when: false
  check_mode: false

- name: "Section 2 | PRELIM | Check if postfix package is installed"
  command: "{{ prelim_check_package_command[ansible_os_family] }} postfix"
  register: postfix_installed
  changed_when: false
  failed_when: false
  check_mode: false
  
- name: "Section 2 | PRELIM | Check for rsyncd service"
  shell: "set -o pipefail;
      systemctl show rsync | grep LoadState | cut -d = -f 2"
  args:
      executable: /bin/bash
  register: rsyncd_service_status
  changed_when: false
  check_mode: false

- name: "Section 2 | PRELIM | Check for ntalk service"
  shell: "set -o pipefail;
      systemctl show ntalk | grep LoadState | cut -d = -f 2"
  args:
      executable: /bin/bash
  register: ntalk_service_status
  changed_when: false
  check_mode: false