pipeline {
    agent { label "rhel" }
    environment {
        AWS_DEFAULT_REGION="us-east-2"
    }
    stages {
        stage('Hello') {
            steps {
                sh '''
                    aws --version
                    aws ec2 describe-instances
                '''
            }
        }
    }
}