---
- name: "OPEN CUSTOM PORT | Allow Port1"
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ cis_port1 }}"
    ctstate: NEW
    jump: ACCEPT
    comment: Allow Custom Port1
  when:
    - cis_port1 is defined
  tags:
      - cis_open_port1

- name: "OPEN CUSTOM PORT | Allow Port2"
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ cis_port2 }}"
    ctstate: NEW
    jump: ACCEPT
    comment: Allow Custom Port2
  when:
    - cis_port2 is defined
  tags:
      - cis_open_port2