#################### Iptables #####################
- name: get current state of the firewall
  community.general.iptables_state:
    state: saved
    path: /tmp/iptables
  check_mode: true
  changed_when: false
  register: iptables_state
  when:
      - cis_99_deny_ssh
  tags:
    - level2
    - lockdown

- name: show current state of the firewall
  ansible.builtin.debug:
    var: iptables_state.initial_state
  when:
      - cis_99_deny_ssh
  tags:
    - level2
    - lockdown
####

- name: "SECTION 99 | LOCKDOWN | Block SSH Login"
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    ctstate: NEW
    syn: match
    jump: DROP
    comment: Reject new SSH connections
    action: insert
    state: absent
    rule_num: 1

- name: "SECTION 99 | LOCKDOWN | Block SSH Login"
  iptables:
    ip_version: ipv4
    chain: "{{ item }}"
    policy: DROP
  with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]
  when:
      - cis_99_deny_ssh
  tags:
    - level2
    - lockdown
- name: "SECTION 99 | LOCKDOWN | Block SSH Login"
  iptables:
      ip_version: ipv6
      chain: "{{ item }}"
      policy: DROP
  with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]
  when:
      - cis_99_deny_ssh
  tags:
    - level2
    - lockdown

- name: Save current state of the firewall in system file
  community.general.iptables_state:
    state: saved
    path: /etc/sysconfig/iptables
  when:
      - cis_99_deny_ssh
  tags:
    - level2
    - lockdown
- name: save current state of the firewall in system file
  community.general.iptables_state:
    ip_version: ipv6
    table: filter
    state: saved
    path: /etc/iptables/rules.v6
  when:
      - cis_99_deny_ssh
  tags:
    - level2
    - lockdown


####
- name: get current state of the firewall
  community.general.iptables_state:
    state: saved
    path: /tmp/iptables
  check_mode: true
  changed_when: false
  register: iptables_state
  when:
      - cis_99_deny_ssh
  tags:
    - level2
    - lockdown

- name: show current state of the firewall
  ansible.builtin.debug:
    var: iptables_state.initial_state
  when:
      - cis_99_deny_ssh
  tags:
    - level2
    - lockdown
###############################################################

- name: "SECTION 99 | LOCKDOWN | Further Harden sshd_config"
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      # SECTION 99
      # 99.5.2.1
      PubkeyAuthentication yes
      PasswordAuthentication no
      KbdInteractiveAuthentication no 
      KerberosAuthentication no
      ChallengeResponseAuthentication no 
      HostbasedAuthentication no 
      GSSAPIAuthentication no 
      GSSAPIKeyExchange no
      # 99.5.2.2
      RekeyLimit 512M\s+6h
      # 99.5.2.3
      AllowAgentForwarding no
      AllowTcpForwarding no 
      AllowStreamLocalForwarding no 
      PermitTunnel no 
      PermitUserRC no 
      GatewayPorts no
      # 99.5.2.5
      StrictModes yes
      # 99.5.2.8
      UsePrivilegeSeparation sandbox
      AcceptEnv LANG LC
  when:
      - cis_99_harden_sshd
  tags:
    - level2
    - lockdown

- name: "SECTION 99 | LOCKDOWN | Further Harden hosts.deny"
  lineinfile:
    path: /etc/hosts.deny
    line: 'ALL: ALL'
    state: present
    create: yes
  when:
      - cis_99_harden_hosts
  tags:
    - level2
    - lockdown

- name: "SECTION 99 | LOCKDOWN | Remove authorized_keys file"
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ authorized_keys_file_location }}"
  when:
      - cis_99_remove_keys
  tags:
    - level2
    - lockdown