---
# tasks file for centos-cis

- name: Check OS version and family
  debug:
      msg: "Executing Compliance Role on {{ ansible_distribution }} {{ ansible_distribution_major_version }} Instance!"
  # when:
  #     - ansible_os_family == "RedHat"
  tags:
      - always

- name: Check ansible version
  fail:
      msg: You must use ansible 2.3 or greater!
  when: not ansible_version.full is version_compare('2.3', '>=')
  tags:
      - always

- include_tasks: section1-partitions.yml
  when: cis_partitions|d(true)|bool
  tags: partitions

- include_tasks: section1.yml
  when: cis_section1
  tags: section1
  
- include_tasks: section2.yml
  when: cis_section2
  tags: section2

- include_tasks: section3.yml
  when: cis_section3
  tags: section3

- include_tasks: section4.yml
  when: cis_section4
  tags: section4

- include_tasks: section5.yml 
  when: cis_section5
  tags: section5

- include_tasks: section6.yml
  when: cis_section6
  tags: section6

- include_tasks: lynis-rpm.yml
  when: 
    - cis_lynis|d(true)|bool
    - ansible_os_family == "RedHat"
  tags: lynis

- include_tasks: lynis-deb.yml
  when: 
    - cis_lynis|d(true)|bool
    - ansible_os_family == "Debian"
  tags: lynis

- include_tasks: section99.yml
  when: cis_section99|d(false)|bool
  tags: lockdown

- include_tasks: custom-ports.yml
  when: cis_open_ports|d(true)|bool
  tags: ports

- include_tasks: section1-end.yml
  when: cis_section1
  tags: section1

