---
# Following tasks will be executed at the end

- name: "SCORED | 1.1.2 | PATCH | Ensure separate partition exists for /tmp | enable and start/restart tmp.mount"
  copy:
      src: "{{ tmp_mount_file[ansible_os_family] }}"
      dest: /etc/systemd/system/tmp.mount
      owner: root
      group: root
      mode: 0644
      force: true
      remote_src: true
  notify:
      - systemd enable tmp.mount
  when:
      - cis_rule_1_1_2
    #   - ansible_os_family == 'RedHat'
  tags:
      - level1
      - scored
      - patch
      - rule_1.1.2


- name: "SCORED | 1.1.3 | PATCH | Ensure nodev option set on /tmp partition\n
        SCORED | 1.1.4 | PATCH | Ensure nosuid option set on /tmp partition\n
        SCORED | 1.1.5 | PATCH | Ensure noexec option set on /tmp partition\n
        | drop custom tmp.mount"
  ini_file:
      path: "{{ item }}"
      section: Mount
      option: Options
      value: "{{ tmp_mount_options[ansible_os_family] }}"
      no_extra_spaces: true
  with_items:
      - "{{ tmp_mount_file[ansible_os_family] }}"
      - /etc/systemd/system/tmp.mount
  notify:
      - systemd enable tmp.mount
  when:
    #   - ansible_os_family == 'RedHat'
      - cis_rule_1_1_3
      - cis_rule_1_1_4
  tags:
      - level1
      - scored
      - patch
      - rule_1.1.3
      - rule_1.1.4

- name: "SCORED | 3.5.2.1 | PATCH | Ensure default ipv4 deny firewall policy"
  iptables:
    ip_version: ipv4
    chain: "{{ item }}"
    policy: DROP
  with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]
  when:
    - cis_rule_3_5_2_1
    - cis_firewall == "iptables"
    - cis_setup_firewall
  notify:
      - rpm-iptables save
      - deb-iptables save
  tags:
    - level1
    - scored
    - patch
    - rule_3.5.2.1