---
- name: "SCORED | 1.1.3 | PATCH | Ensure nodev option set on /tmp partition\n
        SCORED | 1.1.4 | PATCH | Ensure nosuid option set on /tmp partition\n
        SCORED | 1.1.5 | PATCH | Ensure noexec option set on /tmp partition\n
        | drop custom tmp.mount"
  ini_file:
      path: "{{ item }}"
      section: Mount
      option: Options
      value: "{{ tmp_mount_options[ansible_os_family] }}"
      no_extra_spaces: true
  with_items:
      - "{{ tmp_mount_file[ansible_os_family] }}"
      - /etc/systemd/system/tmp.mount
  notify:
      - systemd enable tmp.mount
  when:
    #   - ansible_os_family == 'RedHat'
      - cis_rule_1_1_3
      - cis_rule_1_1_4
  tags:
      - level1
      - scored
      - patch
      - rule_1.1.3
      - rule_1.1.4

- name: "SCORED | 1.1.6 | PATCH | Ensure separate partition exists for /var"
  shell: mount | grep "on /var "
  register: var_mounted
  changed_when: false
  failed_when: false
  when:
      - cis_rule_1_1_6
  tags:
      - level2
      - scored
      - patch
      - rule_1.1.6
      

- name: "SCORED | 1.1.7 | PATCH | Ensure separate partition exists for /var/tmp"
  shell: mount | grep "on /var/tmp "
  register: var_tmp_mounted
  changed_when: false
  failed_when: false
  when:
      - cis_rule_1_1_7
  tags:
      - level2
      - scored
      - patch
      - rule_1.1.7