# TMP PARTITION TASKS ARE EXECUTED AT THE END 1.1.2 - 1.1.5
---
- name: "SCORED | 1.1.2 | PATCH | Ensure separate partition exists for /tmp | enable and start/restart tmp.mount"
  copy:
      src: "{{ tmp_mount_file[ansible_os_family] }}"
      dest: /etc/systemd/system/tmp.mount
      owner: root
      group: root
      mode: 0644
      force: true
      remote_src: true
  notify:
      - systemd start tmp.mount
  when:
      - cis_rule_1_1_2
  tags:
      - level2
      - scored
      - patch
      - rule_1.1.2



- name: "SCORED | 1.1.3 | PATCH | Ensure nodev option set on /tmp partition\n
        SCORED | 1.1.4 | PATCH | Ensure nosuid option set on /tmp partition\n
        SCORED | 1.1.5 | PATCH | Ensure noexec option set on /tmp partition\n
        | drop custom tmp.mount"
  ini_file:
      path: "{{ item }}"
      section: Mount
      option: Options
      value: "{{ tmp_mount_options[ansible_os_family] }}"
      no_extra_spaces: true
  with_items:
      - "{{ tmp_mount_file[ansible_os_family] }}"
      - /etc/systemd/system/tmp.mount
  notify:
      - systemd start tmp.mount
  when:
      - cis_rule_1_1_3
      - cis_rule_1_1_4
  tags:
      - level1
      - scored
      - patch
      - rule_1.1.3
      - rule_1.1.4

- name: "PATCH | enable tmp.mount"
  systemd:
      name: tmp.mount
      enabled: yes
      masked: no
      state: stopped
  when:
      - cis_rule_1_1_2
  tags:
      - level2
      - scored
      - patch
      - rule_1.1.2